### ISSUE TITLE
Image replace

### ISSUE THREAD

**Issue by medeirosrafael** [wrklst/docxmustache#27]
When i try run the example, the image isn't replaced. No error generated. It's works with images?

**Comment by tobiasvielmetter** [comment]
It does work with images and is in production usage with it. Not sure what the issue is, but it’s likely on your side. You might want to do some debugging to see what’s actually going on. Eg are the images resized, placed into the docx file etc. This library technically works well, but is not well documented nor has it sufficient error reporting. Therefore more digging on the implementation side is necessary.

**Comment by medeirosrafael** [comment]
I got it. In Libreoffice i need put the {{img_url}} tag in a ghost field (LOL!).
![Screenshot from 2019-08-19 08-36-04](https://user-images.githubusercontent.com/13787877/63262473-6e9be100-c25c-11e9-8c9f-caca1d2ec488.png)

**Comment by medeirosrafael** [comment]
@tobiasvielmetter i was having a problem.. when my condition is not satisfied, a blank space still in document.
Example:
"
BLA BLA BLA BLA BLA
{{#myCondition}}
 xxxxxxxxxxxxxxxx
{{/myCondition}}
ZZZZZZZZZZZZZZZZZZZZz
"

If myCondition is false the result is:
"
BLA BLA BLA BLA BLA

ZZZZZZZZZZZZZZZZZZZZz
"
instead of
"
BLA BLA BLA BLA BLA
ZZZZZZZZZZZZZZZZZZZZz
"

I solved locally adding 
```
 preg_match_all("'(<w:p>.*?</w:p>)'si", $this->word_doc, $matches);
        foreach ($matches[0] as $match) {
            if (strpos($match, '<w:t xml:space="preserve"></w:t>') !== false) {
                $this->word_doc = str_replace($match, '', $this->word_doc);
            }
        }
```
in DocxMustache.php line 156..

Can i make a merge request?

**Comment by tobiasvielmetter** [comment]
Not sure this makes sense. If a \n / <br> is outside of the condition, it will be shown, no matter if the condition is met. The way to do your condition would be the following instead, so you dont have any unnecessary new lines, even if the condition is not met:
"
BLA BLA BLA BLA BLA{{#myCondition}}

xxxxxxxxxxxxxxxx
{{/myCondition}}
ZZZZZZZZZZZZZZZZZZZZz
"
