### ISSUE TITLE
Error calling execute function

### ISSUE THREAD

**Issue by rmundel** [wrklst/docxmustache#34]
I'm getting this when calling for ->execute()

```
"message": "Trying to access array offset on value of type null",
    "exception": "ErrorException",
    "file": "vendor/wrklst/docxmustache/src/WrkLst/DocxMustache/DocxMustache.php",
    "line": 224,
```

I'm using laravel 6.x and docxmustache dev-master (the latest release 0.0.33 have lots of messed up paths)

Also would be nice to have the creating taking place at 'temp/' subfolder.
Now, the storagePathPrefix set the pathing for the whole instance.

The project looks promising, great work!

**Comment by rmundel** [comment]
Just found out the problem happens when the function ImageReplacer calls $this->AddContentType('jpeg');

**Comment by tobiasvielmetter** [comment]
Hi @rmundel, not sure what the jpeg conversion has to do with this error. The error you are receiving seems to have something to do with https://github.com/wrklst/docxmustache/blob/95420aab35efdcb423573da3f8b14cffbcf3ad6c/src/WrkLst/DocxMustache/DocxMustache.php#L224 not having the offset that the function is calling for some reason. I wont be able to debug your circumstances, so you'll have to check for yourself what is actually happening in your environment. Feel free to reopen this debugging and error analysis, in case there is an issue with the class and not with your setup. Thanks for participating.
