### ISSUE TITLE
Cannot process file

### ISSUE THREAD

**Issue by aramirez92** [wrklst/docxmustache#36]
https://github.com/wrklst/docxmustache/blob/95420aab35efdcb423573da3f8b14cffbcf3ad6c/src/WrkLst/DocxMustache/DocxMustache.php#L379

I've commented this line to fix no processing file.

**Comment by tobiasvielmetter** [comment]
I would definitely not comment this out. Have you done some debugging to understand why you get the processing error? By default just accepting the image in the format you receive is not good practice and will not make it into this class. If anything this could be rewritten to reformat the image into any docx compatible format. Thanks
